# --- 新加/需確認的鍵 ---
scenario: assign_dynamic # free | assign_static | assign_dynamic | mdp
random_seed: 42
p_compliance: 1.0 # 先設 1.0 看純決策效果，再引入不遵從
max_reassignments: 2
mdp_replan_period_s: 10
park_duration_s: 600
allow_violation: true # True: 候選可含保留位，靠 penalty 懲罰

enable_emissions: false

mdp:
  # 論文示例權重（可調）
  alpha_drive: 0.3
  beta_walk: 0.6
  gamma_violation: 10.0
  m_reserved_mgmt: 5
  M_violate: 50
  lambda_var: 1.0
  base_fee: 0

  # 每區步行代價（沒有就用：保留30 / 一般40）
  walking_proxy:
    PA_G_W1: 40
    PA_G_E1: 40
    PA_F_W: 30
    PA_D_E: 30

  # 熱度（效益的一部分）
  zone_heat:
    PA_G_W1: 5
    PA_G_E1: 10
    PA_F_W: 10
    PA_D_E: 10

  # 使用者偏好加成
  user_bonus:
    normal: 0
    family: 10
    disabled: 10
    vip: 20

  # 違規懲罰矩陣（乘以 gamma_violation）
  penalty_matrix:
    normal: { general: 0, family: 3, disabled: 3 }
    family: { general: 1, family: 0, disabled: 2 }
    disabled: { general: 2, family: 2, disabled: 0 }
    vip: { general: 1, family: 3, disabled: 3 }



# # Tunable parameters for experiments
# scenario: "assign_dynamic"    # free | assign_static | assign_dynamic
# random_seed: 42
# sim_duration_s: 3600          # simulation time (seconds)

# # Demand (vehicles per hour total)
# vehPerHour: 900

# # User type shares (must sum <= 1; remaining goes to 'normal')
# share_family: 0.10
# share_disabled: 0.03

# # Parking stock ratios (of total capacity defined in parking.add.xml)
# ratio_special_family: 0.08    # ~8% family spaces
# ratio_special_disabled: 0.03  # ~3% disabled spaces

# # Guidance / behavior
# p_compliance: 0.85            # probability a driver follows assignment
# max_reassignments: 1          # dynamics limit to reduce oscillation
# search_fail_k: 2              # free search: attempts before switching zone

# # Information / detection
# poll_interval_s: 2            # TraCI polling for availability
# info_delay_s: 5               # simulate info staleness
# detect_accuracy: 0.97         # availability sensing accuracy (optional)

# # Enforcement (for violations; normal users shouldn't use special areas)
# enable_enforcement: true
# p_detect: 0.7                 # detection probability per sweep
# enforcement_period_s: 30      # sweep frequency
# p_violate_normal: 0.02        # base violation probability for normal users

# # Emissions (enable in SUMO config if needed)
# enable_emissions: false       # set true and configure in config.sumocfg
